### ISSUE TITLE
-E is not at option of ssh-keygen

### ISSUE THREAD

**Issue by pavel-si** [wercker/step-add-to-known_hosts#13]
Starting with 2.0.3, builds fail with 
```
unknown option -- E
usage: ssh-keygen [-q] [-b bits] [-t dsa | ecdsa | ed25519 | rsa | rsa1]
                  [-N new_passphrase] [-C comment] [-f output_keyfile]
       ssh-keygen -p [-P old_passphrase] [-N new_passphrase] [-f keyfile]
       ssh-keygen -i [-m key_format] [-f input_keyfile]
       ssh-keygen -e [-m key_format] [-f input_keyfile]
       ssh-keygen -y [-f input_keyfile]
       ssh-keygen -c [-P passphrase] [-C comment] [-f keyfile]
       ssh-keygen -l [-f input_keyfile]
       ssh-keygen -B [-f input_keyfile]
       ssh-keygen -D pkcs11
       ssh-keygen -F hostname [-f known_hosts_file] [-l]
       ssh-keygen -H [-f known_hosts_file]
       ssh-keygen -R hostname [-f known_hosts_file]
       ssh-keygen -r hostname [-f input_keyfile] [-g]
       ssh-keygen -G output_file [-v] [-b bits] [-M memory] [-S start_point]
       ssh-keygen -T output_file -f input_file [-v] [-a rounds] [-J num_lines]
                  [-j start_line] [-K checkpt] [-W generator]
       ssh-keygen -s ca_key -I certificate_identity [-h] [-n principals]
                  [-O option] [-V validity_interval] [-z serial_number] file ...
       ssh-keygen -L [-f input_keyfile]
       ssh-keygen -A
       ssh-keygen -k -f krl_file [-u] [-s ca_public] [-z version_number]
                  file ...
       ssh-keygen -Q -f krl_file file ...
```

**Comment by followbl** [comment]
I went through both options...

1. upgrade openssh-client and server
2. revert the script and add it to source

I went with option 2...but it'd be great for this step to support both as this seems to be a breaking change...

Btw, is there a way to specify a specific version of a step? I looked through wercker documentation and could not find it (def could've missed it)

**Comment by felipefdl** [comment]
@followbl 
- wercker/add-to-known_hosts@2.0.1

**Comment by tvb** [comment]
@felipefdl you mean like so in `wercker.yml`?
```
- add-to-known_hosts@2.0.1:
        hostname: bitbucket.org
        fingerprint: 97:8c:1b:f2:6f:14:6b:5c:3b:ec:aa:46:46:74:7c:40
```

**Comment by felipefdl** [comment]
@tvb yep

```yml
- wercker/add-to-known_hosts@2.0.1:
        hostname: bitbucket.org
        fingerprint: 97:8c:1b:f2:6f:14:6b:5c:3b:ec:aa:46:46:74:7c:40
```

**Comment by tvb** [comment]
Hmm it still fails. Not related to the `-E` error tho
```
Searching for keys that match fingerprint 97:8c:1b:f2:6f:14:6b:5c:3b:ec:aa:46:46:74:7c:40
Skipped adding a key to known_hosts, it did not match the fingerprint (SHA256:zzXQOXSRBEiUtuE8AikJYKwbHaxvSc0ojez9YXaGp1A)
```

**Comment by followbl** [comment]
@felipefdl thanks for the note...this helped. I would recommend making this change at a minimum a minor patch...but would possibly even recommend it as a major as it's not backwards compatible with ubuntu 12.04 which currently supplies 6.7 openssh...just a suggestion though, going through slack and here it seems that this broke quite a few peoples builds yesterday.

**Comment by reclaro** [comment]
@tvb you can try to put the fingerprint of the server in the SHA256 version, that should fix your issue. If it is about bitbucket keys, you can find public key fingerprints at this address:
https://confluence.atlassian.com/bitbucket/use-the-ssh-protocol-with-bitbucket-cloud-221449711.html

**Comment by tvb** [comment]
@reclaro thanks, I figured it out but forgot to update this issue. It is worrying that this braking change got merged without warning and during weekends. It broke a lot of deployments for us and all hell broke lose 😭

**Comment by reclaro** [comment]
It has been deployed a new version of this step which introduces a new flag called 'use-md5', if it is specified to "true" it forces the use of the '-E' flag, by default the flag is not used now.

If you have OpenSSH version >=6.8 and you have fingerprint key in MD5 format then you have to choice to get the step working, either add the use-md5 in your wercker.yml or use the SHA256 format for your fingerprint key. In the README there are some examples. I am going to close this issue.
